# Assignment 2                                       
## (Ashutosh Raichurkar 001306059)

# Frozen Lake
![](projectw2.gif)
## Abstract
The goal of this game is to go from the starting state (S) to the goal state (G) by walking only on frozen tiles (F) and avoid holes (H). However, the ice is slippery, so you won't always move in the direction you intend (stochastic environment)

## Actions
 |Num||Action|
 |---||:----:|
 |0||Move Left|
 |1||Move Down|
 |2||Move Right|
 |3||Move Up|
 
 ## Reward
 Reward is 0 for every step taken, 0 for falling in the hole, 1 for reaching the final goal
 
 
 ## Grid
 
 The letters in the Grid have the following significance
- S: initial state
- F: frozen lake
- H: hole
- G: the goal
- Square: indicates the current position of the player

# Reinforcemnt Learning
## Model
![](Reinforcement_L.png)

## 
![](RL.jpg)

In [9]:
#importing the required libraries
import gym
import numpy as np
import pandas as pd
import random
import time
from IPython.display import clear_output

In [10]:
#Creating an environment for the game
env = gym.make("FrozenLake-v0")

In [11]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

## What are the states, the actions and the size of the Q-Table

In [12]:
print("Number of Action:",action_space_size)
print("Number of States:",state_space_size)

Number of Action: 4
Number of States: 16


In [13]:
action_size = env.action_space.n
state_size = env.observation_space.n

q_table = np.zeros((state_size, action_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ans: The size of the Q-Table is equal is 16 x 4

## Lets undersand the Environment by playing the game manually and calculating the reward for each action

In [14]:
env.reset()
env.render()
action = 1
new_state, reward, done, info = env.step(action)#execute the action
print("Reward:",reward)
env.render()
action = 2
new_state, reward, done, info = env.step(action)#execute the action
print("Reward:",reward)
env.render()


SFFF
FHFH
FFFH
HFFG
Reward: 0.0
  (Down)
SFFF
FHFH
FFFH
HFFG
Reward: 0.0
  (Right)
SFFF
FHFH
FFFH
HFFG


## Establish a baseline performance. How well did your RL Q-Learning do on your problem?

## Lets create a baseline model to play the game

In [15]:
num_episodes = 5000
max_steps_per_episode = 99 #max number of steps that the agent is allowed to take while playing the game

learning_rate = 0.7    # The value of alpha = learning rate in the bellman's equation 
discount_rate = 0.8     # Dicount rate is the penalty after the moving from one state to the other, in order to complete the game in less number of steps

exploration_rate = 1          #Exploration rate
max_exploration_rate = 1      #max Exploration Rate
min_exploration_rate = 0.01   #Min Exploration Rate
exploration_decay_rate = 0.01 #Decay rate

In [16]:
rewards_all_episodes = []  #hold all the rewards from each episode
#q learning algo
for episode in range(num_episodes): #every thing that happens in a episode
    state = env.reset() #reset the state of envt to start
    done = False #track if the episode is finished
    rewards_current_episode = 0 
    
    for step in range(max_steps_per_episode): #every thing that happens in a single time step in a episode

    # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1) #whether the agent eill explore 
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) # exploit envt
        else:
            action = env.action_space.sample() #explore
        
        # action is choosen
        new_state, reward, done, info = env.step(action)#execute the action
        
        #update q table for Q(s,a)
        q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action])
        state = new_state #set current state to new
        rewards_current_episode += reward #update the reward
        if done == True: #check if last action ended the episode
            break
            
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode) #decay exploration rate
    rewards_all_episodes.append(rewards_current_episode) #append the episode reward
    
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
clt=0

print("Average reward per thousand episodes\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    clt=clt+sum(r/1000)
    count += 1000
print("Total Score",clt/(num_episodes/1000))

Average reward per thousand episodes

1000 :  0.21500000000000016
2000 :  0.34900000000000025
3000 :  0.35000000000000026
4000 :  0.34200000000000025
5000 :  0.3710000000000003
Total Score 0.32540000000000024


## Ans: By implementing the baseline model we get reward for 5000 episodes is 0.3

## By changing the hyper-parameters like Learning Rate, Decay Rate and Hyper Parameter to improve the reward return by the agent

In [17]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.03
discount_rate = 0.91

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [19]:
rewards_all_episodes = []  #hold all the rewards from each episode
#q learning algo
for episode in range(num_episodes): #every thing that happens in a episode
    state = env.reset() #reset the state of envt to start
    done = False #track if the episode is finished
    rewards_current_episode = 0 
    
    for step in range(max_steps_per_episode): #every thing that happens in a single time step in a episode

    # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1) #whether the agent eill explore 
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) # exploit envt
        else:
            action = env.action_space.sample() #explore
        
        # action is choosen
        new_state, reward, done, info = env.step(action)#execute the action
    
        #update q table for Q(s,a)
        q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action])
        #print(n,q_table[state, action],state,action)
        state = new_state #set current state to new
        rewards_current_episode += reward #update the reward
        if done == True: #check if last action ended the episode
            break
            
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode) #decay exploration rate
    rewards_all_episodes.append(rewards_current_episode) #append the episode reward
    
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
clt=0

print("Average reward per thousand episodes\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    clt=clt+sum(r/1000)
print("Total Score",clt/(num_episodes/1000))

Average reward per thousand episodes

1000 :  0.05000000000000004
2000 :  0.1560000000000001
3000 :  0.36600000000000027
4000 :  0.4930000000000004
5000 :  0.5600000000000004
6000 :  0.5520000000000004
7000 :  0.6590000000000005
8000 :  0.6470000000000005
9000 :  0.6970000000000005
10000 :  0.6370000000000005
Total Score 0.48170000000000035


## Inserting a nested For-Loop in order to find the optimal value of learning Rate, Discount Rate and Decay Rate

In [ ]:
rewards_all_episodes = []
ctr=0
alpha = [0.05,0.07,0.09]
dk = [0.7,0.8,0.99]
pk = [0.001,0.002,0.003]
for x in alpha:
    for y in dk:
        for z in pk:
            learning_rate = x
            discount_rate = y
            exploration_decay_rate = z
            for episode in range(num_episodes): #every thing that happens in a episode
                state = env.reset() #reset the state of envt to start
                done = False #track if the episode is finished
                rewards_current_episode = 0 
                for step in range(max_steps_per_episode): #every thing that happens in a single time step in a episode
                    exploration_rate_threshold = random.uniform(0, 1) #whether the agent eill explore 
                    if exploration_rate_threshold > exploration_rate:
                        action = np.argmax(q_table[state,:]) # exploit envt
                    else:
                        action = env.action_space.sample() #explore
                    new_state, reward, done, info = env.step(action)#execute the action
                    
                    q_table[state, action] =  q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action])
                    
                    state = new_state #set current state to new
                    rewards_current_episode += reward
                    if done == True:
                        break
                exploration_rate = min_exploration_rate + \
                (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
                
                rewards_all_episodes.append(rewards_current_episode)
                ctr = ctr+1
            
            rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
            count = 1000
            alg = np.sum(rewards_per_thosand_episodes)
            print("--------------------------")
            print(alg/ctr)
            print("Learning Rate",x)
            print("Discount Rate",y)
            print("Decay Rate",z)
            
            

## Training the Agent with the optimal values for Learning Rate, Decay Rate and Disocunt rate

In [20]:
num_episodes = 10000
max_steps_per_episode = 99 #max number of steps that the agent is allowed to take while playing the game

learning_rate = 0.07   # The value of alpha = learning rate in the bellman's equation 
discount_rate = 0.99     # Dicount rate is the penalty after the moving from one state to the other, in order to complete the game in less number of steps

exploration_rate = 1          #Exploration rate
max_exploration_rate = 1      #max Exploration Rate
min_exploration_rate = 0.01   #Min Exploration Rate
exploration_decay_rate = 0.001 #Decay rate

In [22]:
rewards_all_episodes = []  #hold all the rewards from each episode
#q learning algo
for episode in range(num_episodes): #every thing that happens in a episode
    state = env.reset() #reset the state of envt to start
    done = False #track if the episode is finished
    rewards_current_episode = 0 
    
    for step in range(max_steps_per_episode): #every thing that happens in a single time step in a episode

    # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1) #whether the agent eill explore 
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) # exploit envt
        else:
            action = env.action_space.sample() #explore
        
        # action is choosen
        new_state, reward, done, info = env.step(action)#execute the action
        #n=n+1
        #update q table for Q(s,a)
        q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action])
        #print(n,q_table[state, action],state,action)
        state = new_state #set current state to new
        rewards_current_episode += reward #update the reward
        if done == True: #check if last action ended the episode
            break
            
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode) #decay exploration rate
    rewards_all_episodes.append(rewards_current_episode) #append the episode reward
    
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
clt=0

print("Average reward per thousand episodes\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    clt=clt+sum(r/1000)
print("Total Score",clt/(num_episodes/1000))

Average reward per thousand episodes

1000 :  0.06200000000000005
2000 :  0.22600000000000017
3000 :  0.3980000000000003
4000 :  0.5700000000000004
5000 :  0.6490000000000005
6000 :  0.6830000000000005
7000 :  0.6730000000000005
8000 :  0.6700000000000005
9000 :  0.7040000000000005
10000 :  0.6860000000000005
Total Score 0.5321000000000005


## Letting the Agent play with Q-values from the Q-Table

In [23]:
env.reset()
episode_steps = []
rewards_current_episode = 0
for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps_per_episode):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(q_table[state,:])
        
        new_state, reward, done, info = env.step(action)
        rewards_current_episode += reward #update the reward
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
        
            env.render()
            if reward == 1:
                print("You have Reached the Goal")
            else: 
                print("You got ine the hole")
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
    episode_steps.append(step)
env.close()
print("Score",rewards_current_episode)

****************************************************
EPISODE  0
  (Left)
SFFF
FHFH
FFFH
HFFG
You got ine the hole
Number of steps 11
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
You have Reached the Goal
Number of steps 16
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
You have Reached the Goal
Number of steps 22
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
You have Reached the Goal
Number of steps 69
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
You have Reached the Goal
Number of steps 17
Score 4.0


In [31]:
for episode in range(5):
    state = env.reset() #Reseting the environment
    done = False
    print("*****Episode****", episode+1,"******\n\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward , done, info = env.step(action)
        
        if done:
            clear_output(wait = True)
            env.render()
            if reward == 1:
                print("***You reached the goal")
                time.sleep(3)
            else:
                print("***you fell in the hole***")
                time.sleep(3)
            clear_output(wait = True)
            break
        state = new_state
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
***you fell in the hole***


## What is the Average number of steps taken per episodes

In [24]:
print("Average Number of steps per episode",np.mean(episode_steps))

Average Number of steps per episode 27.0


## Try a policy other than maxQ(s',a'). How did it change the baseline performance?

In [33]:
num_episodes = 5000
max_steps_per_episode = 99 #max number of steps that the agent is allowed to take while playing the game

learning_rate = 0.7    # The value of alpha = learning rate in the bellman's equation 
discount_rate = 0.8     # Dicount rate is the penalty after the moving from one state to the other, in order to complete the game in less number of steps

exploration_rate = 1          #Exploration rate
max_exploration_rate = 1      #max Exploration Rate
min_exploration_rate = 0.01   #Min Exploration Rate
exploration_decay_rate = 0.01 #Decay rate

In [34]:
rewards_all_episodes = []  #hold all the rewards from each episode
#q learning algo
for episode in range(num_episodes): #every thing that happens in a episode
    state = env.reset() #reset the state of envt to start
    done = False #track if the episode is finished
    rewards_current_episode = 0 
    
    for step in range(max_steps_per_episode): #every thing that happens in a single time step in a episode

    # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1) #whether the agent eill explore 
        if exploration_rate_threshold > exploration_rate:
            action = np.argmin(q_table[state,:]) # exploit envt
        else:
            action = env.action_space.sample() #explore
        
        # action is choosen
        new_state, reward, done, info = env.step(action)#execute the action
        
        #update q table for Q(s,a)
        q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.min(q_table[new_state, :]) - q_table[state, action])
        #print(n,q_table[state, action],state,action)
        state = new_state #set current state to new
        rewards_current_episode += reward #update the reward
        if done == True: #check if last action ended the episode
            break
            
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode) #decay exploration rate
    rewards_all_episodes.append(rewards_current_episode) #append the episode reward
    
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
clt=0

print("Average reward per thousand episodes\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    clt=clt+sum(r/1000)
print("Total Score",clt/(num_episodes/1000))
print("Average Number of steps per episode",np.mean(episode_steps))

Average reward per thousand episodes

1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
Total Score 0.0
Average Number of steps per episode 34.0204


## What are the Rewards? Why do we choose them
A reward in RL is part of the feedback from the environment. When an agent interacts with the environment, he can observe the changes in the state and reward signal through his actions. He can then use this reward signal (can be positive for a good action or negative for a bad action) to draw conclusions about how to behave in a state.The goal, in general, is to solve a given task with the maximum reward possible. For the game of Frozen Lake we get a reward 1 every time the agent reaches the goal and reward 0 if the agent takes falls in the hole

## How did you choose your decay rate and starting epsilon? Try at least one additional value for epsilon and the decay rate. How did it change the baseline performance? What is the value of epsilon when if you reach the max steps per episode?
The value of epsilon originally takes in 1 as the agent needs to explore the environment as the Q-table is initially 0. The decay rate is small as the reward system is sparse therefore allowing the agent to explore most of the environment before the reward


In [27]:
num_episodes = 10000
max_steps_per_episode = 99 #max number of steps that the agent is allowed to take while playing the game

learning_rate = 0.07   # The value of alpha = learning rate in the bellman's equation 
discount_rate = 0.99     # Dicount rate is the penalty after the moving from one state to the other, in order to complete the game in less number of steps

exploration_rate = 1          #Exploration rate
max_exploration_rate = 1      #max Exploration Rate
min_exploration_rate = 0.01   #Min Exploration Rate
exploration_decay_rate = 0.001 #Decay rate

In [29]:
rewards_all_episodes = []  #hold all the rewards from each episode
#q learning algo
episode_steps = []
for episode in range(num_episodes): #every thing that happens in a episode
    state = env.reset() #reset the state of envt to start
    done = False #track if the episode is finished
    rewards_current_episode = 0 
    
    for step in range(max_steps_per_episode): #every thing that happens in a single time step in a episode

    # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1) #whether the agent eill explore 
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) # exploit envt
        else:
            action = env.action_space.sample() #explore
        
        # action is choosen
        new_state, reward, done, info = env.step(action)#execute the action
        
        #update q table for Q(s,a)
        q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action])
        #print(n,q_table[state, action],state,action)
        state = new_state #set current state to new
        rewards_current_episode += reward #update the reward
        if done == True: #check if last action ended the episode
            break
        if step == max_steps_per_episode:
            print(exploration_rate)
    episode_steps.append(step)        
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode) #decay exploration rate
    rewards_all_episodes.append(rewards_current_episode) #append the episode reward
    
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
clt=0

print("Average reward per thousand episodes\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    clt=clt+sum(r/1000)
print("Total Score",clt/(num_episodes/1000))

Average reward per thousand episodes

1000 :  0.04500000000000003
2000 :  0.21000000000000016
3000 :  0.4070000000000003
4000 :  0.5490000000000004
5000 :  0.5820000000000004
6000 :  0.6700000000000005
7000 :  0.6740000000000005
8000 :  0.6800000000000005
9000 :  0.7020000000000005
10000 :  0.6900000000000005
Total Score 0.5209000000000004


## Does Q-learning use value-based or policy-based iteration?
Q-Learning uses value based iteration


## What is meant by expected lifetime value in the Bellman equation?
The expected lifetime value is calculated in the bellman equation by maxQ'(s',a'), as it helps us calculate the expeced final reward, depending on the actions taken

# References
- https://www.youtube.com/watch?v=nyjbcRQ-uQ8&list=PLZbbT5o_s2xoWNVdDudn51XM8lOuZ_Njv
- https://medium.com/@m.alzantot/deep-reinforcement-learning-demysitifed-episode-2-policy-iteration-value-iteration-and-q-978f9e89ddaa

# License
Copyright 2020 Ashutosh Raichurkar

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Conclusion:
By using Q-Learning we are training the agent to play the game and improve the acuracy by changing the hyper-parameters like Learning Rate, Discount Rate and Decay Rate 
